[package]
name = "input_system"
version = "0.1.0"
authors = ["Perceval62 <perrier.vincent0210@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[profile.release]
lto = true